# Generated by Django 4.2.7 on 2023-11-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeismicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('origin_time', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('magnitude_Mb', models.FloatField(blank=True, null=True)),
                ('magnitude_Ms', models.FloatField(blank=True, null=True)),
                ('magnitude_Ml', models.FloatField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-origin_time',),
                'unique_together': {('origin_time', 'location_name')},
            },
        ),
        migrations.CreateModel(
            name='FocalMechanismSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
                ('strike1', models.FloatField(blank=True, null=True)),
                ('dip1', models.FloatField(blank=True, null=True)),
                ('rake1', models.FloatField(blank=True, null=True)),
                ('strike2', models.FloatField(blank=True, null=True)),
                ('dip2', models.FloatField(blank=True, null=True)),
                ('rake2', models.FloatField(blank=True, null=True)),
                ('P', models.FloatField(blank=True, null=True)),
                ('B', models.FloatField(blank=True, null=True)),
                ('T', models.FloatField(blank=True, null=True)),
                ('magnitude_Mw', models.FloatField(blank=True, null=True)),
                ('manner', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seismic_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='seismic_events.seismicevent')),
            ],
        ),
    ]
